import pandas as pd

sample_data = pd.read_csv('sample.csv')
# print(sample_data.Region.value_counts())
# print(sample_data.groupby('Region').Region.count())
# print(sample_data.sort_values(by='len', ascending = False))
# print(sample_data.UnitsSold.dtype)
# sample_data.UnitsSold = sample_data.UnitsSold.astype('float64')
# print(sample_data.dtypes)
# print(sample_data.loc[:, 'UnitsSold'])
# print(sample_data.isnull())
# sample_data = sample_data.fillna('Unknown')
# print(sample_data.isnull())
# sample_data.Region = sample_data.Region.replace('East', 'Easttt')
# print(sample_data)
# sample_data = sample_data.rename(columns={'UnitsSold': 'UnitSold'})
print(sample_data)
